### PR TITLE
Fix more allocator traits

### LINKED ISSUE #84: Cannot build with clang-11 and libc++ in C++20 mode.
This component fails to compile due to not using `std::allocator_traits` with clang-11 and libc++ in C++20 mode.

```
boost/wave/util/flex_string.hpp:547:25: error: no type named 'size_type' in 'std::__1::allocator<char>'
    typedef typename A::size_type size_type;
            ~~~~~~~~~~~~^~~~~~~~~
```

* [build log](https://github.com/boostorg/wave/files/4447651/build-log.txt)
* [config.jam](https://github.com/boostorg/wave/files/4447652/config.jam.txt)

Command used to build boost:

```
b2 --layout=system
   --project-config=/mnt/c/Workspace/vcpkg/buildtrees/boost/x64-linux-dbg/config.jam
   --prefix=/mnt/c/Workspace/vcpkg/packages/boost_x64-linux/debug
   --libdir=/mnt/c/Workspace/vcpkg/packages/boost_x64-linux/debug/lib
   --exec-prefix=/mnt/c/Workspace/vcpkg/packages/boost_x64-linux/debug/bin
   --includedir=/mnt/c/Workspace/vcpkg/packages/boost_x64-linux/debug/../include
   --cmakedir=/mnt/c/Workspace/vcpkg/packages/boost_x64-linux/debug/share/boost
   --build-dir=/mnt/c/Workspace/vcpkg/buildtrees/boost/x64-linux-dbg/build
   --without-graph_parallel --without-mpi --without-python
   --includedir=/mnt/c/Workspace/vcpkg/packages/boost_x64-linux/include
   architecture=x86 address-model=64
   variant=debug threading=multi
   link=static runtime-link=shared
   debug-symbols=on install
```

The `log` component has a similar issue: https://github.com/boostorg/log/issues/114

### PR DESCRIPTION
**Pull request by jefftrull**
If merged this will resolve #84. Thanks to @qis for the assistance.

### CODE REVIEW

**Comment by glenfe** [comment]
@jefftrull Something like:

```cpp
namespace boost {
namespace wave {
namespace util {

#if !defined(BOOST_NO_CXX11_ALLOCATOR)
using std::allocator_traits;
#else
template<class A>
struct allocator_traits {
    typedef typename A::value_type value_type;
    typedef typename A::pointer pointer;
    // Fill in the rest as needed.
};
#endif

} // util
} // wave
} // boost
```

**Comment by jefftrull** [comment]
Looks like this problem has been solved by a few other libraries and appears to be in the public interface of Container - is it worth simply using that one? https://www.boost.org/doc/libs/1_72_0/doc/html/boost/container/allocator_traits.html

**Comment by glenfe** [comment]
@jefftrull That would be fine too if there are no objections to Boost.Wave taking a dependency on Boost.Container (which it doesn't right now, I believe).

**Comment by Lastique** [comment]
@glenfe @igaztanaga Another option would be to move `allocator_traits` from Boost.Container to Boost.Core. There are other places where we need `allocator_traits` but not the rest of Boost.Container.

**Comment by jefftrull** [comment]
Upon reflection I don't think it makes sense to add a dependency for the benefit of this one string class within one library. Unless `allocator_traits` goes into Core I'll stick with a minimal local version.

**Comment by jefftrull** [comment]
The Travis job has been hung for > 24h so I'm just going to merge it.

**Comment by glenfe** [comment]
@Lastique https://github.com/boostorg/core/commit/c31e23b36294bc3958b04deef62123abce0204b9

**Comment by Lastique** [comment]
@glenfe Thank you Glen.

**Comment by jefftrull** [comment]
Will refactor to use that in 1.74.

**Pull request merged**
